---
title: "Assignment 1: Introduction"
author: "Isabelle Kuehn"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
I have very little experience with data analytics, R, and GitHub. I took a computer science course in my sophomore year of high school where I was introduced to GitHub, but we dealt with it minimally and I did not work enough with the system to feel confident in any training I did. I would say I am more confident with data analytics through my experience with statistics and Python coursework I have completed in undergrad.

2. Are there any components of the course about which you feel confident?

> Answer: 
Given that I don't have much experience with data analytics or the software in the course, I would say there isn't a component of the course I feel very confident with, but I am excited to gain confidence throughout the semester.

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
Absolutely. I am most apprehensive about working with R. I have previous coding experience with MATLAB and Python, but both I have found difficult for me to understand easily. Coding in general makes me pretty nervous as I don't find myself very skilled with technical programming skills, but I look forward to working with R becasue I know I will use it a lot in my future.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 
https://github.com/ivkuehn/EDE_Fall2025

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
